Stock.Web/Models/Domain/CidadeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class CidadeModel
    {
    }
}

Stock.Web/Models/Domain/EntradaProdutoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class EntradaProdutoModel
    {
    }
}

Stock.Web/Models/Domain/EstadoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class EstadoModel
    {
    }
}

Stock.Web/Models/Domain/FornecedorModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class FornecedorModel
    {
    }
}

Stock.Web/Models/Domain/GrupoProdutoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class GrupoProdutoModel
    {
    }
}

Stock.Web/Models/Domain/InventarioEstoqueModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class InventarioEstoqueModel
    {
    }
}

Stock.Web/Models/Domain/LocalArmazenamentoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class LocalArmazenamentoModel
    {
    }
}

Stock.Web/Models/Domain/MarcaProdutoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class MarcaProdutoModel
    {
    }
}

Stock.Web/Models/Domain/PaisModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class PaisModel
    {
    }
}

Stock.Web/Models/Domain/PerfilModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class PerfilModel
    {
    }
}

Stock.Web/Models/Domain/Produtomodel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class Produtomodel
    {
    }
}

Stock.Web/Models/Domain/SaidaProdutoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class SaidaProdutoModel
    {
    }
}

Stock.Web/Models/Domain/Tipos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class Tipos
    {
    }
}

Stock.Web/Models/Domain/UnidadeMedidaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class UnidadeMedidaModel
    {
    }
}

Stock.Web/Models/Domain/UsuarioModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stock.Web.Models.Domain
{
    public class UsuarioModel
    {
    }
}

Stock.Web/Controllers/Cadastro/CadPaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stock.Web.Controllers.Cadastro
{
    public class CadPaisController : Controller
    {
        // GET: CadPais
        public ActionResult Index()
        {
            return View();
        }
    }
}

Stock.Web/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stock.Web.Controllers
{
    public class ContaController : Controller
    {
        // GET: Conta
        public ActionResult Index()
        {
            return View();
        }
    }
}

Stock.Web/Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stock.Web.Controllers
{
    public class GraficoController : Controller
    {
        // GET: Grafico
        public ActionResult Index()
        {
            return View();
        }
    }
}

Stock.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stock.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Sobre()
        {
            return View();
        }

        
    }
}

Stock.Web/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stock.Web.Controllers
{
    public class RelatorioController : Controller
    {
        // GET: Relatorio
        public ActionResult Index()
        {
            return View();
        }
    }
}

Stock.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Cadastros
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Grupos de produtos", "Index", "CadGrupoProduto")</li>
                            <li>@Html.ActionLink("Marcas de produtos", "Index", "CadMarcaProduto")</li>
                            <li>@Html.ActionLink("Locais de armazenamento", "Index", "CadLocalArmazenamento")</li>
                            <li>@Html.ActionLink("Unidades de medida", "Index", "CadUnidadeMedida")</li>
                            <li>@Html.ActionLink("Produtos", "Index", "CadProduto")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Países", "Index", "CadPais")</li>
                            <li>@Html.ActionLink("Estados", "Index", "CadEstado")</li>
                            <li>@Html.ActionLink("Cidades", "Index", "CadCidade")</li>
                            <li>@Html.ActionLink("Fornecedores", "Index", "CadFornecedor")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Perfis de Usuários", "Index", "CadPerfil")</li>
                            <li>@Html.ActionLink("Usuários", "Index", "CadUsuario")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Operações
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Entrada de produtos", "Index", "OperEntradaProduto")</li>
                            <li>@Html.ActionLink("Saída de produtos", "Index", "OperSaidaProduto")</li>
                            <li>@Html.ActionLink("Lançamento de perdas de produtos", "Index", "OperLancamentoPerdaProduto")</li>
                            <li>@Html.ActionLink("Inventário de estoque", "Index", "OperInventario")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Relatórios
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Posição do Estoque", "Index", "RelatPosicaoEstoque")</li>
                            <li>@Html.ActionLink("Ressuprimento", "Filtro", "RelatRessuprimento")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Gráficos
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Perdas por mês", "PerdaMes", "Grafico")</li>
                            <li>@Html.ActionLink("Entradas vs saídas por mês", "EntradaSaidaMesa", "Grafico")</li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>